name: Cypress mini slack notify
on:
  workflow_dispatch:
jobs:
  cypress-test:
    name: Run on Chrome 89
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Slack notification with Cypress screenshots & videos
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channels: 'cypress-results'
          workdir: cypress
          message-text: 'To facilitate debugging these production test failures, the Cypress screenshots and videos have been posted to this thread. :mag:'