name: Upload artifacts after build completes
on:
  workflow_dispatch:

jobs:
  cypress-test:
    name: Run on Chrome 89
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.16.0-chrome89-ff86
    steps:
      - uses: actions/checkout@v2

      - name: Install Cypress with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify

      - name: Run Cypress tests
        run: npm run test:ci:full

      - name: house keeping
        if: always()
        run: |
          mkdir downloaded-artifacts
          rm -rf node_modules

      - uses: actions/download-artifact@v2
        if: always()
        with:
          name: my-test-artifact
          
      - name: Display structure of downloaded files
        if: always()
        run: ls

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
            name: my-test-artifact
            path: ${{ github.workspace }}